development:
  # Register in sandbox veritrans and get your keys here:
  # https://dashboard.sandbox.midtrans.com/settings/config_info
  client_key: "SB-Mid-client-kP34xDzlvI5mSU37"
  server_key: "SB-Mid-server-k4plJ-jwu2s_m3W0i5WA7fSo"
  api_host: https://api.sandbox.midtrans.com

production:
  # Register and get your keys here:
  # https://dashboard.midtrans.com/settings/config_info
  client_key: <%= ENV['VERITRANS_CLIENT_KEY'] %>
  server_key: <%= ENV['VERITRANS_SERVER_KEY'] %>
  api_host: https://api.midtrans.com

staging:
  client_key: <%= ENV['VT_SANDBOX_CLIENT_KEY'] %>
  server_key: <%= ENV['VT_SANDBOX_SERVER_KEY'] %>
  api_host: https://api.sandbox.midtrans.com
